{{ if eq .Values.storage "openstack" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gold
parameters:
  availability: nova
provisioner: kubernetes.io/cinder
{{ end }}

