---
name: Build and Publish Filer

on:
  push:
    branches: ['testing-gh-action']
    tags: ['*']

  workflow_dispatch:
    inputs:
      profile:
        description: Profile name
        required: false
        default: tesk-core-filler

jobs:
  build-from-source:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout elixir-cloud-aai/tesk-core
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            elixircloud/${{ github.workflow }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./deployment/containers/filer.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
